name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List files in the root directory
        run: ls -al

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yml

  pushtoargorepo:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v3

      - name: Update values.yaml
        run: |
          echo "image: ecr.aws.amazonaws.com/your-repo-name:latest" >> helm/values.yaml

      - name: Push to Argo repo
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add helm/values.yaml
          git commit -m "Update Docker image version in Helm chart"
          git push
