name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List files in the root directory
        run: ls -al

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yml
Pushtoargorepo:
   runs-on: ubuntu-latest
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v2
      - name: update values.yaml
        run: |
          echo "image: ecr.aws.amazonaws.com/your-repo-name:latest" >> helm/values.yaml  
      - name: push to argo repo
        run: |
          git commands to commit and push the changes to the helmrepo

